// Generated by CoffeeScript 1.6.3
(function() {
  var Witch, feels, formatStat, generateName, loadUI, natures, pc, ranks, roles,
    __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  document.title = "Night Witches";

  formatStat = function(num) {
    if (num < 0) {
      return "" + num;
    } else {
      return "+" + num;
    }
  };

  ranks = ["Sergeant", "Junior Lieutenant", " Lieutenant", "Senior  Lieutenant", "Captain", "Major"];

  feels = ["love", "trust", "admire", "respect", "hate", "resent", "pity", "fear"];

  natures = {
    hawk: {
      name: "Hawk",
      moves: [
        {
          name: "Suka",
          desc: "You enjoy +1 ongoing when acting like a hooligan. When you act like a lady you are marked."
        }, {
          name: "People’s Hero",
          desc: "Name the high-ranking official who has taken a personal interest in your career."
        }, {
          name: "11.4 Meters Tip-to-Tip",
          desc: "When you want to land in some new place, you can ask “Is it remotely possible to land there?” and the GM will tell you. If the answer is yes, you don’t need to roll the Wheels Down move."
        }, {
          name: "As Seen In Pravda",
          desc: "Use +medals instead of +guts when you Tempt Fate."
        }, {
          name: "Miss Sverdlovsk 1939",
          desc: "Advance the first time you have sex with each of: a Senior Lieutenant, a Captain, a Major, a Lieutenant Colonel, or a Colonel."
        }
      ],
      marks: ["Suffer the death of a friend or lover.", "Witness the death of a comrade.", "Give your aircraft a personality.", "Make a friend or take a lover.", "Tell a self-aggrandizing lie.", "Share a painful truth about yourself.", "Acquire a dread or superstition.", "Put duty before health or love.", "Advance and grow.", "Tell a war story.", "Tell a story of home.", "Embrace Death and face your final destiny."]
    },
    owl: {
      name: "Owl",
      moves: [
        {
          name: "Greater Good",
          desc: "Rewrite an unused mark to read “Abandon a comrade and Advance”"
        }, {
          name: "Prodigal Daughter",
          desc: "Whenever you return to the Regiment after being assumed captured or dead, advance as if it were the end of a duty station."
        }, {
          name: "Intense Navigation",
          desc: "To find a target at night, you don’t need to Wayfind if you instead take a mark or 1-harm, your choice. "
        }, {
          name: "Pull Rank",
          desc: "Take +1 forward when you Act Up if you outrank the target."
        }, {
          name: "Political Thought",
          desc: "When you Eyeball you may also ask “Is there evidence of violation of Articles 58 and 133?” "
        }
      ],
      marks: ["Suffer the death of a friend or lover.", "Witness the death of a comrade.", "Share a premonition.", "Make a friend or take a lover.", "Inform the authorities.", "Publicly shame a comrade.", "Earn a medal you don't deserve.", "Put safety or love before duty.", "Advance and grow.", "Tell a war story.", "Tell a story of home.", "Embrace Death and face your final destiny."]
    },
    pigeon: {
      name: "Pigeon",
      moves: [
        {
          name: "Shit Talking",
          desc: "Call out another player character you despise at a debriefing and roll +Regard. On a 10+ hold three; on 7-9 hold one. Spend your holds, one for one, to give this person -1 forward."
        }, {
          name: "Forbidden Love",
          desc: "When you take a lover, keep it secret. If discovered, face the consequences together or abandon your lover and advance."
        }, {
          name: "Androgynous",
          desc: "You can Act Up by acting like a man - not a hooligan - using +guts. On a miss you are marked."
        }, {
          name: "Bedside Manner",
          desc: "When you treat someone who has been badly hurt, roll +luck. On a hit it isn’t so bad. On 7-9 finding out takes a lot of time, energy or resources, GM chooses."
        }, {
          name: "Enthusiastic Support",
          desc: "When you are Wingman, choose the consequences for the aircrew leading the Attack Run."
        }
      ],
      maxRegard: 5,
      maxPromos: 3,
      marks: ["Suffer the death of a friend or lover.", "Witness the death of a comrade.", "Give your aircraft a personality.", "Make a friend or take a lover.", "Comfort a dying friend.", "Betray a friend or lover.", "Disgrace yourself or your uniform.", "Ignore a problem until it overwhelms.", "Advance and grow.", "Tell a war story.", "Tell a story of home.", "Embrace Death and face your final destiny."]
    },
    raven: {
      name: "Raven",
      moves: [
        {
          name: "To Hell With Death",
          desc: "When you would be marked, name a player character who is marked instead if you wish."
        }, {
          name: "Permanent File",
          desc: "When you submit an official report to your superiors, roll +skill. On a 10+, choose 2. On 7-9, choose 1: Mark someone; Change accepted truth of a situation; Add one to the mission pool"
        }, {
          name: "Fortune’s Fool",
          desc: "Choose a single move. Replace the rolled stat with +Luck when you roll trigger it."
        }, {
          name: "Voron",
          desc: "When you steal a treasured possession from someone, they are marked. If the “treasured possession” is their lover or their future, advance."
        }, {
          name: "Sacrifice",
          desc: "When you are sent to the hospital to recover from combat injuries, you may choose your assignment, squadron, section and aircraft when you return."
        }
      ],
      marks: ["Suffer the death of a friend or lover.", "Witness the death of a comrade.", "Share a premonition.", "Tell the unvarnished truth.", "Claim something as your own.", "Ignore a problem until it overwhelms.", "Change posts for the wrong reasons.", "Act against your best interests.", "Advance and grow.", "Tell a war story.", "Tell a story of home.", "Embrace Death and face your final destiny."]
    },
    sparrow: {
      name: "Sparrow",
      moves: [
        {
          name: "Dark Bargain",
          desc: "You can elect to be marked in order to remove all harm from yourself or another."
        }, {
          name: "Ghosts",
          desc: "Choose a dead comrade and hold three. When you ask your friend for help, spend your holds one for one to succeed as if you had rolled a 10+. Every time you do this you are also harmed or marked by the experience, your choice. "
        }, {
          name: "Transcendent Love",
          desc: "Choose your one and only lover.  Your bond is unshakable. The first time you take the mark “Embrace Death”, immediately erase it."
        }, {
          name: "Murky Past",
          desc: "You guard your history carefully. Choose two things you are hiding: Valuable training, prominent family, political connections, a strange secret, portable wealth. Define them whenever you want. Reveal either of these aspects of your past to save the day, make an impression or ruin someone."
        }, {
          name: "Ambition",
          desc: "Once per duty station, do something explicitly against orders, then Tempt Fate and advance."
        }
      ],
      maxRegard: 3,
      maxMoves: 5,
      marks: ["Suffer the death of a friend or lover.", "Witness the death of a comrade.", "Share a premonition.", "Call dangerous attention to yourself.", "Speak truth to power.", "Spread a vicious rumour.", "Reveal a secret.", "Act against your best interests.", "Advance and grow.", "Tell a war story.", "Tell a story of home.", "Embrace Death and face your final destiny."]
    }
  };

  roles = [
    {
      name: "Adventurer",
      desc: "You can bring a plane <strong>Wheels Down</strong> well."
    }, {
      name: "Dreamer",
      desc: "You can weather an <strong>Informal Interview</strong> well."
    }, {
      name: "Leader",
      desc: "You can lead an <strong>Attack Run</strong> well."
    }, {
      name: "Misanthrope",
      desc: "You can <strong>Scrounge</strong> well."
    }, {
      name: "Protector",
      desc: "You can <strong>Repair</strong> well."
    }, {
      name: "Zealot",
      desc: "You can help the section during <strong>Debrief</strong> by criticizing a fellow airwoman."
    }
  ];

  generateName = function() {
    var givenNames, gn, sn, surnames;
    givenNames = ["Evgeniya (Zhenya)", "Galina (Galya)", "Olga (Olya)", "Alexandra (Sasha)", "Yekaterina (Katya)", "Elena (Lena)", "Irina (Ira)", "Elizaveta (Liza)", "Lyudmila (Lyuda)", "Svetlana (Sveta)", "Natalya (Natasha)", "Lyubov (Lyuba)", "Yuliya (Yulya)", "Tatyana (Tanya)", "Ksenya (Ksyusha)", "Valentina (Valya)", "Mariya (Masha)", "Anastasiya (Nastya)", "Darya (Dasha)", "Anna (Anka)", "Larisa (Lara)", "Tamara (Toma)", "Yelena (Lena)", "Oksana (Ksana)", "Vera (Veruschka)", "Nadezhda (Nadya)", "Sofia (Sonya)", "Marina", "Polina (Polya)", "Valeria (Lira)", "Diana (Dina)", "Alyona (Alya)", "Nina (Ninochka)"];
    surnames = ["Unvarova", "Shchepkina", "Yubkina", "Alexandrova", "Ventseslava", "Zavorokhina", "Avdeyeva", "Yegorova", "Kuznetsova", "Petrova", "Berezovskya", "Zubova", "Andreyeva", "Bobkova", "Golovina", "Yusupova", "Trushina", "Sheremeteva", "Vavilova", "Zubareva", "Isayeva", "Kazakova", "Vyrpayeva", "Kurdina", "Moskvina", "Rudina", "Samsonova", "Batkina", "Grishina", "Usilova", "Filipova", "Khramova", "Tsvetkova", "Chazova", "Nemtseva", "Lyugashova", "Meladina", "Dezhnyova", "Yermolayeva", "Zhurova", "Malinovskya", "Gordievskya", "Vorapaeva", "Kryukova", "Stepnova", "Toropova", "Myasnikova", "Primakova", "Rezansova", "Chernova", "Shirmanova", "Osina", "Papanova", "Pomelova", "Kirsanova", "Lavrova", "Shmeleva", "Mirova", "Fomenkova", "Maltseva", "Burtsova", "Stezhenskya", "Fedorova", "Vasilievskya", "Turbina"];
    gn = givenNames[Math.floor(Math.random() * givenNames.length)];
    sn = surnames[Math.floor(Math.random() * surnames.length)];
    return "" + gn + " " + sn;
  };

  Witch = (function() {
    function Witch() {
      this.rank = 0;
      this.promos = 0;
      this.guts = 0;
      this.luck = 0;
      this.skill = 0;
      this.medals = 0;
      this.regard = [];
      this.marks = [];
      this.moves = [];
    }

    Witch.prototype.updateBinding = function() {
      var maxPromo, maxRegard, _ref, _ref1, _ref2, _ref3, _ref4, _ref5, _ref6;
      $("header h1").html("<span class='rank'>" + ranks[this.rank] + " </span>" + this.name);
      $("#nat_role").text("" + ((_ref = this.nature) != null ? _ref.name : void 0) + " " + ((_ref1 = this.role) != null ? _ref1.name : void 0));
      $(".role_desc").html((_ref2 = this.role) != null ? _ref2.desc : void 0);
      $("#guts span").text(formatStat(this.guts));
      $("#luck span").text(formatStat(this.luck));
      $("#skill span").text(formatStat(this.skill));
      $("#medals span").text(formatStat(this.medals));
      if (this.medals >= 4) {
        $("#plusmedal").attr('disabled', 'disabled');
      } else {
        $("#plusmedal").removeAttr('disabled');
      }
      maxPromo = (_ref3 = (_ref4 = this.nature) != null ? _ref4.maxPromo : void 0) != null ? _ref3 : 4;
      if (this.guts >= 3 || this.promos >= maxPromo) {
        $("#promoguts").attr('disabled', 'disabled');
      }
      if (this.luck >= 3 || this.promos >= maxPromo) {
        $("#promoluck").attr('disabled', 'disabled');
      }
      if (this.skill >= 3 || this.promos >= maxPromo) {
        $("#promoskill").attr('disabled', 'disabled');
      }
      maxRegard = (_ref5 = (_ref6 = this.nature) != null ? _ref6.maxRegard : void 0) != null ? _ref5 : 4;
      if (this.regard >= maxRegard) {
        $("#addregard").attr('disabled', 'disabled');
      }
      if ((pc.station != null) === true) {
        return $("#changestation").attr("disabled", "disabled");
      }
    };

    Witch.prototype.rollStat = function(stat) {
      var d1, d2, newVal;
      d1 = Math.floor(Math.random() * 6 + 1);
      d2 = Math.floor(Math.random() * 6 + 1);
      newVal = d1 + d2 + this[stat];
      return $("footer p:first").html("Rolled " + d1 + " + " + d2 + " + " + stat + " = <strong>" + newVal + "</strong> (+1 if Regard applies)");
    };

    Witch.prototype.assignNature = function(nature) {
      this.nature = nature;
      return this.rebindNatureButtons();
    };

    Witch.prototype.updateNatureMoves = function() {
      var m, moves;
      $(".naturemove").remove();
      moves = (function() {
        var _i, _len, _ref, _ref1, _results;
        _ref = this.nature.moves;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          m = _ref[_i];
          if (_ref1 = m.name, __indexOf.call(this.moves, _ref1) >= 0) {
            _results.push("<li class='naturemove ui-li-static ui-body-inherit'><h3>" + m.name + "</h3><p>" + m.desc + "</p></li>");
          } else {
            _results.push("");
          }
        }
        return _results;
      }).call(this);
      return $(".nm_header").after(moves.join(""));
    };

    Witch.prototype.buildRegardSlots = function() {
      var f, i, maxRegard, r, r2, reg, regardslots, v, vals, _i, _len, _ref, _ref1;
      maxRegard = (_ref = this.nature.maxRegard) != null ? _ref : 4;
      regardslots = $('.regard .ui-content ul');
      regardslots.empty();
      vals = (function() {
        var _i, _len, _results;
        _results = [];
        for (_i = 0, _len = feels.length; _i < _len; _i++) {
          f = feels[_i];
          _results.push("<option>" + f + "</option>");
        }
        return _results;
      })();
      v = vals.join("");
      _ref1 = this.regard;
      for (_i = 0, _len = _ref1.length; _i < _len; _i++) {
        r = _ref1[_i];
        r2 = "<li><div data-role='controlgroup' data-type='horizontal'><select>" + v + "</select><input type='text' data-wrapper-class='controlgroup-textinput ui-btn' placeholder='Person or airplane' /> </div></li>";
        regardslots.append(r2);
        regardslots.find("div:last").controlgroup().find("select").val(r.feeling).selectmenu("refresh", true).end().find("input").val(r.target).textinput();
      }
      reg = (function() {
        var _j, _ref2, _results;
        _results = [];
        for (i = _j = _ref2 = this.regard.length; _ref2 <= maxRegard ? _j < maxRegard : _j > maxRegard; i = _ref2 <= maxRegard ? ++_j : --_j) {
          _results.push("<li class='locked'>LOCKED</li>");
        }
        return _results;
      }).call(this);
      return regardslots.append(reg.join(""));
    };

    Witch.prototype.rebindNatureButtons = function() {
      var m, marks, mk, moves;
      moves = (function() {
        var _i, _len, _ref, _ref1, _results;
        _ref = this.nature.moves;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          m = _ref[_i];
          if (_ref1 = m.name, __indexOf.call(this.moves, _ref1) >= 0) {
            _results.push("<button class='addmove' value='" + m.name + "' disabled='disabled'><strong>" + m.name + ":</strong> " + m.desc + "</button>");
          } else {
            _results.push("<button class='addmove' value='" + m.name + "'><strong>" + m.name + ":</strong> " + m.desc + "</button>");
          }
        }
        return _results;
      }).call(this);
      $("#adv_moves").html(moves.join(""));
      marks = (function() {
        var _i, _len, _ref, _results;
        _ref = this.nature.marks;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          mk = _ref[_i];
          if (__indexOf.call(this.marks, mk) >= 0) {
            _results.push("<button disabled='disabled'>" + mk + "</button>");
          } else {
            _results.push("<button>" + mk + "</button>");
          }
        }
        return _results;
      }).call(this);
      $("#adv_marks").html(marks.join(""));
      return this.buildRegardSlots();
    };

    Witch.prototype.save = function() {
      return localStorage[this.name] = JSON.stringify(this);
    };

    Witch.prototype.load = function(key) {
      var k, v, vals;
      vals = JSON.parse(localStorage[key]);
      for (k in vals) {
        v = vals[k];
        this[k] = v;
      }
      this.rebindNatureButtons();
      this.updateNatureMoves();
      return this.updateBinding();
    };

    return Witch;

  })();

  pc = new Witch();

  loadUI = function() {
    var c, chars, ci, cinfo, k, nat, r, ri, uiroles, v;
    nat = (function() {
      var _results;
      _results = [];
      for (k in natures) {
        v = natures[k];
        _results.push("<li><button value='" + k + "'>" + v.name + "</button></li>");
      }
      return _results;
    })();
    $("#chooseNature ul").html(nat.join(""));
    uiroles = (function() {
      var _i, _len, _results;
      _results = [];
      for (ri = _i = 0, _len = roles.length; _i < _len; ri = ++_i) {
        r = roles[ri];
        _results.push("<li><button value='" + ri + "'>" + r.name + "</button></li>");
      }
      return _results;
    })();
    $("#chooseRole ul").html(uiroles.join(""));
    chars = (function() {
      var _i, _len, _results;
      _results = [];
      for (ci = _i = 0, _len = localStorage.length; _i < _len; ci = ++_i) {
        c = localStorage[ci];
        k = localStorage.key(ci);
        cinfo = JSON.parse(localStorage[k]);
        _results.push("<li><button value='" + k + "' class='pcload'><small>" + ranks[cinfo.rank] + "</small><br/>" + cinfo.name + "</button></li>");
      }
      return _results;
    })();
    return $("#addNew").before(chars.join(""));
  };

  loadUI();

  $(".stats button").on("click", function(e) {
    pc.rollStat($(this).attr("id"));
    return false;
  });

  $("#plusmedal").on("click", function(e) {
    location.hash = "char";
    pc.medals += 1;
    pc.updateBinding();
    pc.save();
    return false;
  });

  $("#promoguts").on("click", function(e) {
    location.hash = "char";
    pc.guts += 1;
    pc.rank += 1;
    pc.promos += 1;
    pc.updateBinding();
    pc.save();
    return false;
  });

  $("#promoluck").on("click", function(e) {
    location.hash = "char";
    pc.luck += 1;
    pc.rank += 1;
    pc.promos += 1;
    pc.updateBinding();
    pc.save();
    return false;
  });

  $("#promoskill").on("click", function(e) {
    location.hash = "char";
    pc.skill += 1;
    pc.rank += 1;
    pc.promos += 1;
    pc.updateBinding();
    pc.save();
    return false;
  });

  $("#addregard").on("click", function(e) {
    var f, newSlot, regardTemplate, v, vals;
    location.hash = "regard";
    newSlot = {
      feeling: "love",
      target: ""
    };
    pc.regard.push(newSlot);
    vals = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = feels.length; _i < _len; _i++) {
        f = feels[_i];
        _results.push("<option>" + f + "</option>");
      }
      return _results;
    })();
    v = vals.join("");
    regardTemplate = "<div data-role='controlgroup' data-type='horizontal'> <select>" + v + "</select> <input type='text' data-wrapper-class='controlgroup-textinput ui-btn' placeholder='Person or airplane' /> </div>";
    $(".regard li.locked:first").removeClass("locked").html(regardTemplate).find("div").controlgroup().find("select").selectmenu().end().find("input").textinput();
    pc.updateBinding();
    pc.save();
    return false;
  });

  $("#changestation").on("click", function(e) {
    pc.station = true;
    pc.updateBinding();
    pc.save();
    return location.hash = "char";
  });

  $(".harm li").on("click", function(e) {
    $(".harm li").removeClass("curr");
    $(this).addClass("curr");
    return false;
  });

  $(".marks").on("click", "button", function(e) {
    var val;
    val = $(this).text();
    pc.marks.push(val);
    $(this).attr("disabled", "disabled");
    pc.save();
    return false;
  });

  $("#adv_moves").on("click", ".addmove", function(e) {
    var val;
    val = $(this).attr("value");
    pc.moves.push(val);
    $(this).attr("disabled", "disabled");
    pc.save();
    pc.updateNatureMoves();
    return false;
  });

  $("#chooseNature button").on("click", function(e) {
    var nature;
    nature = $(this).attr("value");
    pc.assignNature(natures[nature]);
    pc.updateBinding();
    location.hash = "chooseRankStats";
    return false;
  });

  $(".rank_0 button").on("click", function(e) {
    var g, l, s, _ref;
    pc.rank = 0;
    _ref = $(this).attr("value").split(","), g = _ref[0], l = _ref[1], s = _ref[2];
    pc.guts = parseInt(g);
    pc.luck = parseInt(l);
    pc.skill = parseInt(s);
    pc.updateBinding();
    location.hash = "chooseName";
    return false;
  });

  $(".rank_1 button").on("click", function(e) {
    var g, l, s, _ref;
    pc.rank = 1;
    _ref = $(this).attr("value").split(","), g = _ref[0], l = _ref[1], s = _ref[2];
    pc.guts = parseInt(g);
    pc.luck = parseInt(l);
    pc.skill = parseInt(s);
    pc.updateBinding();
    location.hash = "chooseName";
    return false;
  });

  $("#genName").on("click", function(e) {
    return $("#pcName").val(generateName);
  });

  $("#acceptName").on("click", function(e) {
    pc.name = $("#pcName").val();
    pc.updateBinding();
    location.hash = "chooseRole";
    return false;
  });

  $("#chooseRole button").on("click", function(e) {
    var role;
    role = $(this).attr("value");
    pc.role = roles[parseInt(role)];
    pc.updateBinding();
    pc.save();
    location.hash = "char";
    return false;
  });

  $("#addNew").on("click", function(e) {
    pc = new Witch();
    $("#pcName").val(generateName);
    location.hash = "chooseNature";
    return false;
  });

  $("#chooseChar ul").on("click", ".pcload", function(e) {
    var key;
    pc = new Witch();
    key = $(this).attr("value");
    pc.load(key);
    return location.hash = "char";
  });

  $(".regard ul").on("change", "input", function(e) {
    var index;
    index = $(this).closest("li").prevAll().length;
    pc.regard[index].target = $(this).val();
    pc.save();
    return false;
  });

  $(".regard ul").on("change", "select", function(e) {
    var index;
    index = $(this).closest("li").prevAll().length;
    pc.regard[index].feeling = $(this).val();
    pc.save();
    return false;
  });

}).call(this);
